# Generated by Django 6.0.7 on 2026-08-04 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=32)),
                ('channel', models.CharField(help_text='1=MTN, 6=Telecel, 7=AT, 2=Instant Bank Transfer', max_length=8)),
                ('resolved_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('found', 'Found'), ('not_found', 'Not Found')], max_length=16)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('external', 'External (MoMo/Bank)'), ('internal', 'Internal (wallet-to-wallet)')], default='external', max_length=10)),
                ('channel', models.CharField(blank=True, help_text='Required for external transfers', max_length=8)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receiver', models.CharField(max_length=64)),
                ('sublistid', models.CharField(blank=True, max_length=32)),
                ('externalref', models.CharField(max_length=64, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('transactionid', models.CharField(blank=True, max_length=64)),
                ('thirdpartyref', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'), ('otp_pending', 'Awaiting OTP'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending_approval', max_length=20)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('network_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
