# Generated by Django 6.0.7 on 2026-08-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField(help_text='Moolre MoMo network code (e.g. 13=MTN, 6=Telecel, 7=AT)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('payer_msisdn', models.CharField(max_length=20)),
                ('externalref', models.CharField(max_length=64, unique=True)),
                ('transactionid', models.CharField(blank=True, max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('otp_pending', 'Awaiting OTP'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('otp_required', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, help_text='Last raw API payload, for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
