# Generated by Django 6.0.7 on 2026-08-03 08:40

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(max_length=32, unique=True)),
                ('accountname', models.CharField(max_length=255)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('paymentid', models.CharField(blank=True, help_text='Reusable *203*id# payment ID', max_length=32)),
                ('api_enabled', models.BooleanField(default=False)),
                ('callback_url', models.URLField(blank=True)),
                ('secret', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255))),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, max_length=32)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('recipient', models.CharField(blank=True, max_length=64)),
                ('sublist', models.CharField(blank=True, max_length=64)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='wallets.wallet')),
            ],
        ),
    ]
